name: Say hello

on:
  push:
    branches:
      - main
  pull-request:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-24.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola midu!"
      - name: Dime la fecha
        run: date
      - run: ls -l